go:
  version: 1.13.0
  cgo: false
repository:
  path: github.com/Wing924/logstash-exporter
build:
  binaries:
  - name: logstash-exporter
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildDate={{date "2006-01-02T15:04:05Z"}}
tarball:
  files:
  - LICENSE
crossbuild:
  platforms:
  - linux/amd64
  - darwin/amd64
  - windows/amd64
  - freebsd/amd64
